import { IngredientID } from '../ingredients/ingredients';
import {
  FixedArray,
  MainSkill,
  PokemonSpecialty,
  PokemonType,
  SleepType,
} from '../commonTypes';

/**
 * All known Pokemon IDs.
 */
export enum PokemonID {
  Bulbasaur = 'bulbasaur',
  Ivysaur = 'ivysaur',
  Venusaur = 'venusaur',
  Charmander = 'charmander',
  Charmeleon = 'charmeleon',
  Charizard = 'charizard',
  Squirtle = 'squirtle',
  Wartortle = 'wartortle',
  Blastoise = 'blastoise',
  Caterpie = 'caterpie',
  Metapod = 'metapod',
  Butterfree = 'butterfree',
  Rattata = 'rattata',
  Raticate = 'raticate',
  Ekans = 'ekans',
  Arbok = 'arbok',
  Pikachu = 'pikachu',
  Raichu = 'raichu',
  Clefairy = 'clefairy',
  Clefable = 'clefable',
  Jigglypuff = 'jigglypuff',
  Wigglytuff = 'wigglytuff',
  Diglett = 'diglett',
  Dugtrio = 'dugtrio',
  Meowth = 'meowth',
  Persian = 'persian',
  Psyduck = 'psyduck',
  Golduck = 'golduck',
  Mankey = 'mankey',
  Primeape = 'primeape',
  Growlithe = 'growlithe',
  Arcanine = 'arcanine',
  Bellsprout = 'bellsprout',
  Weepinbell = 'weepinbell',
  Victreebel = 'victreebel',
  Geodude = 'geodude',
  Graveler = 'graveler',
  Golem = 'golem',
  Slowpoke = 'slowpoke',
  Slowbro = 'slowbro',
  Magnemite = 'magnemite',
  Magneton = 'magneton',
  Doduo = 'doduo',
  Dodrio = 'dodrio',
  Gastly = 'gastly',
  Haunter = 'haunter',
  Gengar = 'gengar',
  Cubone = 'cubone',
  Marowak = 'marowak',
  Kangaskhan = 'kangaskhan',
  MrMime = 'mrmime',
  Pinsir = 'pinsir',
  Ditto = 'ditto',
  Eevee = 'eevee',
  Vaporeon = 'vaporeon',
  Jolteon = 'jolteon',
  Flareon = 'flareon',
  Chikorita = 'chikorita',
  Bayleef = 'bayleef',
  Meganium = 'meganium',
  Cyndaquil = 'cyndaquil',
  Quilava = 'quilava',
  Typhlosion = 'typhlosion',
  Totodile = 'totodile',
  Croconaw = 'croconaw',
  Feraligatr = 'feraligatr',
  Pichu = 'pichu',
  Cleffa = 'cleffa',
  Igglybuff = 'igglybuff',
  Togepi = 'togepi',
  Togetic = 'togetic',
  Mareep = 'mareep',
  Flaaffy = 'flaaffy',
  Ampharos = 'ampharos',
  Sudowoodo = 'sudowoodo',
  Espeon = 'espeon',
  Umbreon = 'umbreon',
  Slowking = 'slowking',
  Wobbuffet = 'wobbuffet',
  Heracross = 'heracross',
  Houndour = 'houndour',
  Houndoom = 'houndoom',
  Larvitar = 'larvitar',
  Pupitar = 'pupitar',
  Tyranitar = 'tyranitar',
  Slakoth = 'slakoth',
  Vigoroth = 'vigoroth',
  Slaking = 'slaking',
  Sableye = 'sableye',
  Gulpin = 'gulpin',
  Swalot = 'swalot',
  Swablu = 'swablu',
  Altaria = 'altaria',
  Absol = 'absol',
  Wynaut = 'wynaut',
  Spheal = 'spheal',
  Sealeo = 'sealeo',
  Walrein = 'walrein',
  Bonsly = 'bonsly',
  MimeJr = 'mimejr',
  Riolu = 'riolu',
  Lucario = 'lucario',
  Croagunk = 'croagunk',
  Toxicroak = 'toxicroak',
  Magnezone = 'magnezone',
  Togekiss = 'togekiss',
  Leafeon = 'leafeon',
  Glaceon = 'glaceon',
  Sylveon = 'sylveon',
}

/**
 * Represents a Pokemon in Pokemon Sleep.
 */
export interface IPokemonData {
  name: string;
  type: PokemonType;
  sleepType: SleepType;
  specialty: PokemonSpecialty;
  mainSkill: MainSkill;
  ingredients: FixedArray<IngredientID, 3> | FixedArray<IngredientID, 2>;
  baseFrequency: {
    hours: number;
    minutes: number;
    seconds: number;
  };
  carryLimit: number;
  friendshipPointsNeeded: number;
  recruitExperience: number;
  recruitShards: number;
  description: string;
  evolvesInto?: Array<{
    pokemon: PokemonID;
    level?: number;
    candies?: number;
    item?: Item | Item[];
    sleptHours?: number;
  }>;
}

export enum Item {
  ThunderStone = 'ThunderStone',
  MoonStone = 'MoonStone',
  FireStone = 'FireStone',
  LeafStone = 'LeafStone',
  LinkingCord = 'LinkingCord',
  KingsRock = 'KingsRock',
  WaterStone = 'WaterStone',
  IceStone = 'IceStone',
  ShinyStone = 'ShinyStone',
}

/**
 * Map of all known pokemon.
 */
export const Pokemon: { [key in PokemonID]: IPokemonData } = {
  [PokemonID.Bulbasaur]: {
    name: 'Bulbasaur',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.SoftPotato,
      IngredientID.SnoozyTomato,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 13,
      seconds: 20,
    },
    carryLimit: 11,
    friendshipPointsNeeded: 5,
    recruitExperience: 18,
    recruitShards: 39,
    description:
      "It sits still and basks in sunny spots, possibly taking a nap. Perhaps it's trying to absorb nutrients from the seed on its back in order to grow up big, even while sleeping.",
    evolvesInto: [
      {
        pokemon: PokemonID.Ivysaur,
        level: 12,
        candies: 40,
      },
    ],
  },
  [PokemonID.Ivysaur]: {
    name: 'Ivysaur',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.SoftPotato,
      IngredientID.SnoozyTomato,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 55,
      seconds: 0,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 12,
    recruitExperience: 116,
    recruitShards: 245,
    description:
      'It sits still and basks in sunny spots, undergoing photosynthesis. Researchers are divided on whether it is awake or asleep while this happens.',
    evolvesInto: [
      {
        pokemon: PokemonID.Venusaur,
        level: 24,
        candies: 80,
      },
    ],
  },
  [PokemonID.Venusaur]: {
    name: 'Venusaur',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.SoftPotato,
      IngredientID.SnoozyTomato,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 17,
    friendshipPointsNeeded: 20,
    recruitExperience: 574,
    recruitShards: 1033,
    description:
      "This Pokémon emits a pleasant fragrance from the flower on its back as it sleeps. You may sometimes see a Venusaur that's forgotten to retract its long vines before dozing off-perhaps this means it's especially relaxed.",
  },
  [PokemonID.Charmander]: {
    name: 'Charmander',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.WarmingGinger,
      IngredientID.FieryHerb,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 58,
      seconds: 20,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 5,
    recruitExperience: 16,
    recruitShards: 42,
    description:
      "When it curls up to sleep, it's thought to be drawing warmth from the flame on its tail. On quiet nights, it feels like you can almost hear the sound of the flame burning if you listen hard enough.",
    evolvesInto: [
      {
        pokemon: PokemonID.Charmeleon,
        level: 12,
        candies: 40,
      },
    ],
  },
  [PokemonID.Charmeleon]: {
    name: 'Charmeleon',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.WarmingGinger,
      IngredientID.FieryHerb,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 50,
      seconds: 0,
    },
    carryLimit: 15,
    friendshipPointsNeeded: 12,
    recruitExperience: 116,
    recruitShards: 245,
    description:
      'Apparently, Charmeleon sometimes sleeps in a very laid-back posture when relaxed, using its hands as a pillow. It seems its battle fervor completely wears off when it sleeps.',
    evolvesInto: [
      {
        pokemon: PokemonID.Charizard,
        level: 27,
        candies: 80,
      },
    ],
  },
  [PokemonID.Charizard]: {
    name: 'Charizard',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.WarmingGinger,
      IngredientID.FieryHerb,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 40,
      seconds: 0,
    },
    carryLimit: 19,
    friendshipPointsNeeded: 20,
    recruitExperience: 528,
    recruitShards: 1116,
    description:
      "It's been seen looking amazingly relaxed as it nods off, perhaps because it's so confident in its might. The Charizard that you occasionally see sleeping flat on their backs may be particularly strong.",
  },
  [PokemonID.Squirtle]: {
    name: 'Squirtle',
    type: PokemonType.Water,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
      IngredientID.BeanSausage,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 15,
      seconds: 0,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 18,
    recruitShards: 39,
    description:
      "It withdraws its limbs and head into its shell to sleep. It's said to do this to protect itself while sleeping when it's wary of threats. Apparently, it also sometimes rocks contentedly from side to side.",
    evolvesInto: [
      {
        pokemon: PokemonID.Wartortle,
        level: 12,
        candies: 40,
      },
    ],
  },
  [PokemonID.Wartortle]: {
    name: 'Wartortle',
    type: PokemonType.Water,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
      IngredientID.BeanSausage,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 56,
      seconds: 40,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 12,
    recruitExperience: 116,
    recruitShards: 245,
    description:
      "It remains wary of threats as it sleeps with its body tucked into its shell. But even then, its long, furry tail pokes out a bit. Perhaps it's using the fur on its tail to feel out its surroundings.",
    evolvesInto: [
      {
        pokemon: PokemonID.Blastoise,
        level: 27,
        candies: 80,
      },
    ],
  },
  [PokemonID.Blastoise]: {
    name: 'Blastoise',
    type: PokemonType.Water,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
      IngredientID.BeanSausage,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 17,
    friendshipPointsNeeded: 20,
    recruitExperience: 528,
    recruitShards: 1116,
    description:
      "This Pokémon normally sleeps soundly, protected by its tough shell, but it's also been seen sleeping with its belly exposed on very rare occasions. Perhaps this happens when Blastoise feels completely secure in its surroundings and falls fast asleep.",
  },
  [PokemonID.Caterpie]: {
    name: 'Caterpie',
    type: PokemonType.Bug,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.SnoozyTomato,
      IngredientID.GreengrassSoybeans,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 13,
      seconds: 20,
    },
    carryLimit: 11,
    friendshipPointsNeeded: 5,
    recruitExperience: 11,
    recruitShards: 12,
    description:
      'On very rare occasions, Caterpie looks as though it has fallen asleep in the middle of using String Shot. It appears that it drools string instead of saliva while it sleeps.',
    evolvesInto: [
      {
        pokemon: PokemonID.Metapod,
        level: 5,
        candies: 40,
      },
    ],
  },
  [PokemonID.Metapod]: {
    name: 'Metapod',
    type: PokemonType.Bug,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.SnoozyTomato,
      IngredientID.GreengrassSoybeans,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 10,
      seconds: 0,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 7,
    recruitExperience: 29,
    recruitShards: 31,
    description:
      'It stays still when it sleeps to avoid being attacked. Metapod has been confirmed to use Harden even while asleep, possibly to protect its soft innards.',
    evolvesInto: [
      {
        pokemon: PokemonID.Butterfree,
        level: 8,
        candies: 80,
      },
    ],
  },
  [PokemonID.Butterfree]: {
    name: 'Butterfree',
    type: PokemonType.Bug,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.SnoozyTomato,
      IngredientID.GreengrassSoybeans,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 43,
      seconds: 20,
    },
    carryLimit: 21,
    friendshipPointsNeeded: 15,
    recruitExperience: 397,
    recruitShards: 715,
    description:
      'Apparently, it sometimes inadvertently scatters highly toxic dust as it sleeps. Maybe it relaxes its control when it flaps its wings while asleep.',
  },
  [PokemonID.Rattata]: {
    name: 'Rattata',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.GreengrassSoybeans,
      IngredientID.BeanSausage,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 21,
      seconds: 40,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 20,
    description:
      "Its long, sharp fangs grow continuously throughout its life. If it doesn't maintain these fangs, Rattata will apparently grind them in its sleep and wake itself up with the sound.",
    evolvesInto: [
      {
        pokemon: PokemonID.Raticate,
        level: 15,
        candies: 40,
      },
    ],
  },
  [PokemonID.Raticate]: {
    name: 'Raticate',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.GreengrassSoybeans,
      IngredientID.BeanSausage,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 53,
      seconds: 20,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 12,
    recruitExperience: 60,
    recruitShards: 155,
    description:
      'Its sturdy fangs grow steadily, so it grinds its teeth even in its sleep to keep them trimmed. But this may not always be enough-Raticate apparently also gnaws on trees in its sleep sometimes.',
  },
  [PokemonID.Ekans]: {
    name: 'Ekans',
    type: PokemonType.Poison,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.FancyEgg,
      IngredientID.FieryHerb,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 23,
      seconds: 20,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 19,
    description:
      "It's been observed sleeping with its body all coiled. This is thought to be a way for Ekans to quickly turn its head to intimidate enemies, no matter which direction they attack from.",
    evolvesInto: [
      {
        pokemon: PokemonID.Arbok,
        level: 17,
        candies: 40,
      },
    ],
  },
  [PokemonID.Arbok]: {
    name: 'Arbok',
    type: PokemonType.Poison,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.FancyEgg,
      IngredientID.FieryHerb,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 1,
      seconds: 40,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 12,
    recruitExperience: 103,
    recruitShards: 268,
    description:
      "It's been seen displaying its belly while sleeping. Perhaps Arbok is showing its fearsome markings on purpose to keep other Pokémon from coming near it.",
  },
  [PokemonID.Pikachu]: {
    name: 'Pikachu',
    type: PokemonType.Electric,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.FancyEgg,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 45,
      seconds: 0,
    },
    carryLimit: 17,
    friendshipPointsNeeded: 7,
    recruitExperience: 7,
    recruitShards: 20,
    description:
      'While sleeping, it generates electricity in its cheek sacs. Apparently, it may also discharge electricity while it dozes, as if firing off electric shocks in its dreams.',
    evolvesInto: [
      {
        pokemon: PokemonID.Raichu,
        item: Item.ThunderStone,
        candies: 80,
      },
    ],
  },
  [PokemonID.Raichu]: {
    name: 'Raichu',
    type: PokemonType.Electric,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.FancyEgg,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 36,
      seconds: 40,
    },
    carryLimit: 21,
    friendshipPointsNeeded: 18,
    recruitExperience: 326,
    recruitShards: 844,
    description:
      'Apparently, it sometimes sleeps while discharging electricity, its long tail planted like a grounding rod. Take care not to get electrocuted if you approach it!',
  },
  [PokemonID.Clefairy]: {
    name: 'Clefairy',
    type: PokemonType.Fairy,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.Metronome,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.GreengrassSoybeans,
      IngredientID.Honey,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 6,
      seconds: 40,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 7,
    recruitExperience: 49,
    recruitShards: 53,
    description:
      'Clefairy rarely shows itself, but there have been many sightings on the mornings after a full moon. It is said that happiness will come to those who see a Clefairy using Metronome in its sleepâ€”a particularly unusual sight.',
    evolvesInto: [
      {
        pokemon: PokemonID.Clefable,
        item: Item.MoonStone,
        candies: 80,
      },
    ],
  },
  [PokemonID.Clefable]: {
    name: 'Clefable',
    type: PokemonType.Fairy,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.Metronome,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.GreengrassSoybeans,
      IngredientID.Honey,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 24,
    friendshipPointsNeeded: 20,
    recruitExperience: 677,
    recruitShards: 847,
    description:
      "It is said to sleep in remote places on quiet, moonlit nights. Perhaps it's dreaming about its friends in its distant homeland as it peacefully sleeps.",
  },
  [PokemonID.Jigglypuff]: {
    name: 'Jigglypuff',
    type: PokemonType.Fairy,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergyForEveryoneS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.PureOil,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 5,
      seconds: 0,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 7,
    recruitExperience: 23,
    recruitShards: 24,
    description:
      'Jigglypuff is always singing-even in its sleep! You must take care not to be inadvertently put to sleep by the sound of its soothing singing.',
    evolvesInto: [
      {
        pokemon: PokemonID.Wigglytuff,
        item: Item.MoonStone,
        candies: 80,
      },
    ],
  },
  [PokemonID.Wigglytuff]: {
    name: 'Wigglytuff',
    type: PokemonType.Fairy,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergyForEveryoneS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.PureOil,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 48,
      seconds: 20,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 16,
    recruitExperience: 253,
    recruitShards: 273,
    description:
      'Its fine fur has a sublime texture. Wigglytuff has even been seen stroking its belly while fast asleep- perhaps this fur feels nice even to its own touch.',
  },
  [PokemonID.Diglett]: {
    name: 'Diglett',
    type: PokemonType.Ground,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.SnoozyTomato,
      IngredientID.LargeLeek,
      IngredientID.GreengrassSoybeans,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 11,
      seconds: 40,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 20,
    description:
      'It usually lives underground, so at night, it tends to sleep there as well. If you happen to see one asleep above ground, it may be a sign of good luck.',
    evolvesInto: [
      {
        pokemon: PokemonID.Dugtrio,
        level: 20,
        candies: 40,
      },
    ],
  },
  [PokemonID.Dugtrio]: {
    name: 'Dugtrio',
    type: PokemonType.Ground,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.SnoozyTomato,
      IngredientID.LargeLeek,
      IngredientID.GreengrassSoybeans,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 12,
    recruitExperience: 95,
    recruitShards: 284,
    description:
      'These triplets never get separated and they sleep all together. Their teamwork as a trio stays steadfast even when they sleep.',
  },
  [PokemonID.Meowth]: {
    name: 'Meowth',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.DreamShardMagnetS,
    ingredients: [IngredientID.BeanSausage, IngredientID.MoomooMilk],
    baseFrequency: {
      hours: 1,
      minutes: 13,
      seconds: 20,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 5,
    recruitExperience: 8,
    recruitShards: 17,
    description:
      "Meowth loves anything that shines. If you happen to find it sleeping while fondly clutching the coins it's gathered, just watch over it quietly.",
    evolvesInto: [
      {
        pokemon: PokemonID.Persian,
        level: 21,
        candies: 40,
      },
    ],
  },
  [PokemonID.Persian]: {
    name: 'Persian',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.DreamShardMagnetS,
    ingredients: [IngredientID.BeanSausage, IngredientID.MoomooMilk],
    baseFrequency: {
      hours: 0,
      minutes: 50,
      seconds: 0,
    },
    carryLimit: 15,
    friendshipPointsNeeded: 12,
    recruitExperience: 116,
    recruitShards: 245,
    description:
      "Even when asleep, Persian's haughtiness is striking. It appears to clean its face and groom itself even as it sleeps, stretching its lithe body with ease.",
  },
  [PokemonID.Psyduck]: {
    name: 'Psyduck',
    type: PokemonType.Water,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.FancyApple,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 30,
      seconds: 0,
    },
    carryLimit: 8,
    friendshipPointsNeeded: 5,
    recruitExperience: 9,
    recruitShards: 16,
    description:
      'Psyduck is always tormented by headaches-its head seems to cause it pain even during sleep. A Psyduck sleeping peacefully, not clutching its head, is a very rare sight.',
    evolvesInto: [
      {
        pokemon: PokemonID.Golduck,
        level: 25,
        candies: 40,
      },
    ],
  },
  [PokemonID.Golduck]: {
    name: 'Golduck',
    type: PokemonType.Water,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.FancyApple,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 56,
      seconds: 40,
    },
    carryLimit: 11,
    friendshipPointsNeeded: 12,
    recruitExperience: 126,
    recruitShards: 227,
    description:
      "The best swimmer among Pokémon, Golduck has been seen languidly paddling its webbed limbs as it sleeps. Perhaps it's swimming in its dreams.",
  },
  [PokemonID.Mankey]: {
    name: 'Mankey',
    type: PokemonType.Fighting,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.Honey,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 10,
      seconds: 0,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 19,
    description:
      "Mankey may rage even in its dreams, as you often see it sleeping with an infuriated look. Apparently, you'll only find it sleeping free from anger on the rarest of occasions.",
    evolvesInto: [
      {
        pokemon: PokemonID.Primeape,
        level: 21,
        candies: 40,
      },
    ],
  },
  [PokemonID.Primeape]: {
    name: 'Primeape',
    type: PokemonType.Fighting,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.Honey,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 17,
    friendshipPointsNeeded: 12,
    recruitExperience: 116,
    recruitShards: 245,
    description:
      'The ever-angry Primeape rages even in its sleep. It apparently sleeps free from anger on very rare occasions, perhaps when it has exhausted itself.',
  },
  [PokemonID.Growlithe]: {
    name: 'Growlithe',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ExtraHelpfulS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.FieryHerb,
      IngredientID.MoomooMilk,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 11,
      seconds: 40,
    },
    carryLimit: 8,
    friendshipPointsNeeded: 5,
    recruitExperience: 9,
    recruitShards: 16,
    description:
      'It is very protective of its territory. If you see a cute Growlithe asleep and approach it without caution, you may end up on the receiving end of some dozy barking-and learn your lesson the painful way.',
    evolvesInto: [
      {
        pokemon: PokemonID.Arcanine,
        item: Item.FireStone,
        candies: 80,
      },
    ],
  },
  [PokemonID.Arcanine]: {
    name: 'Arcanine',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ExtraHelpfulS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.FieryHerb,
      IngredientID.MoomooMilk,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 41,
      seconds: 40,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 20,
    recruitExperience: 666,
    recruitShards: 1199,
    description:
      "When it feels it has found a supremely comfortable sleeping spot, Arcanine apparently sleeps just like an innocent child-though you'd never expect the pose given Arcanine's usual proud and regal appearance.",
  },
  [PokemonID.Bellsprout]: {
    name: 'Bellsprout',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.LargeLeek,
      IngredientID.SnoozyTomato,
      IngredientID.SoftPotato,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 26,
      seconds: 40,
    },
    carryLimit: 8,
    friendshipPointsNeeded: 5,
    recruitExperience: 9,
    recruitShards: 16,
    description:
      "When it sleeps with its feet planted deep in the ground, it's said to be taking in water from the soil. Perhaps it feels so safe while sleeping that it forgets that it might need to run away.",
    evolvesInto: [
      {
        pokemon: PokemonID.Weepinbell,
        level: 16,
        candies: 40,
      },
    ],
  },
  [PokemonID.Weepinbell]: {
    name: 'Weepinbell',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.LargeLeek,
      IngredientID.SnoozyTomato,
      IngredientID.SoftPotato,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 3,
      seconds: 20,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 12,
    recruitExperience: 73,
    recruitShards: 131,
    description:
      "It's been found sleeping on trees, hanging by the hook on its rear end. Apparently, it sometimes falls to the ground and carries on sleeping, undisturbed.",
    evolvesInto: [
      {
        pokemon: PokemonID.Victreebel,
        item: Item.LeafStone,
        candies: 80,
      },
    ],
  },
  [PokemonID.Victreebel]: {
    name: 'Victreebel',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.LargeLeek,
      IngredientID.SnoozyTomato,
      IngredientID.SoftPotato,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 17,
    friendshipPointsNeeded: 20,
    recruitExperience: 397,
    recruitShards: 715,
    description:
      'Even while asleep, it appears that Victreebel opens its mouth wide to attract prey with the nectar-like acid within it. On very rare occasions, it seems to forget about luring in prey and instead sleeps face down.',
  },
  [PokemonID.Geodude]: {
    name: 'Geodude',
    type: PokemonType.Rock,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.GreengrassSoybeans,
      IngredientID.SoftPotato,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 35,
      seconds: 0,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 19,
    description:
      'This Pokémon sleeps soundly, half-buried in the ground. Apparently, it will sometimes stay fast asleep even when trod on by a mountain climber.',
    evolvesInto: [
      {
        pokemon: PokemonID.Graveler,
        level: 19,
        candies: 40,
      },
    ],
  },
  [PokemonID.Graveler]: {
    name: 'Graveler',
    type: PokemonType.Rock,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.GreengrassSoybeans,
      IngredientID.SoftPotato,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 6,
      seconds: 40,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 12,
    recruitExperience: 67,
    recruitShards: 141,
    description:
      "This Pokémon has been seen rocking back and forth as it sleeps, as if about to roll away at any second. Maybe it's dreaming of rolling down hilly paths.",
    evolvesInto: [
      {
        pokemon: PokemonID.Golem,
        item: Item.LinkingCord,
        candies: 80,
      },
    ],
  },
  [PokemonID.Golem]: {
    name: 'Golem',
    type: PokemonType.Rock,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.GreengrassSoybeans,
      IngredientID.SoftPotato,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 51,
      seconds: 40,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 22,
    recruitExperience: 574,
    recruitShards: 1033,
    description:
      "Apparently, Golem sleeps upside down sometimes, perhaps because it wants to rock itself into a deep sleep, as if it's in a cradle. There's a chance it might roll into you, so it seems best to stay clear.",
  },
  [PokemonID.Slowpoke]: {
    name: 'Slowpoke',
    type: PokemonType.Water,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergizingCheerS,
    ingredients: [
      IngredientID.SlowpokeTail,
      IngredientID.SnoozyTomato,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 35,
      seconds: 0,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 5,
    recruitExperience: 11,
    recruitShards: 12,
    description:
      "This Pokémon is always idle, so it's hard to tell if it's awake or asleep. Even researchers are divided on whether Slowpoke sleeps, but Slowpoke doesn't seem bothered either way.",
    evolvesInto: [
      {
        pokemon: PokemonID.Slowbro,
        level: 28,
        candies: 40,
      },
      {
        pokemon: PokemonID.Slowking,
        item: [Item.KingsRock, Item.LinkingCord],
        candies: 80,
      },
    ],
  },
  [PokemonID.Slowbro]: {
    name: 'Slowbro',
    type: PokemonType.Water,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergizingCheerS,
    ingredients: [
      IngredientID.SlowpokeTail,
      IngredientID.SnoozyTomato,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 3,
      seconds: 20,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 12,
    recruitExperience: 136,
    recruitShards: 209,
    description:
      'Slowbro mostly sleeps at the same time as the Shellder biting its tail. Once in a while, though, Slowbro has been found sleeping with the Shellder still awake.',
  },
  [PokemonID.Magnemite]: {
    name: 'Magnemite',
    type: PokemonType.Steel,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.CookingPowerUpS,
    ingredients: [IngredientID.FieryHerb, IngredientID.PureOil],
    baseFrequency: {
      hours: 1,
      minutes: 36,
      seconds: 40,
    },
    carryLimit: 8,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 20,
    description:
      'The units at its side generate electromagnetic waves that keep it airborne. On rare occasions, perhaps when it sleepily muddles the direction of its waves, it does loops through the air while asleep.',
    evolvesInto: [
      {
        pokemon: PokemonID.Magneton,
        level: 23,
        candies: 40,
      },
    ],
  },
  [PokemonID.Magneton]: {
    name: 'Magneton',
    type: PokemonType.Steel,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.CookingPowerUpS,
    ingredients: [IngredientID.FieryHerb, IngredientID.PureOil],
    baseFrequency: {
      hours: 1,
      minutes: 6,
      seconds: 40,
    },
    carryLimit: 11,
    friendshipPointsNeeded: 12,
    recruitExperience: 95,
    recruitShards: 284,
    description:
      'The three Magnemite are usually linked by a strong magnetic force. They have been spotted sleeping stuck together and drifting apart. Perhaps their magnetism is unstable during sleep.',
    evolvesInto: [
      {
        pokemon: PokemonID.Magnezone,
        item: Item.ThunderStone,
        candies: 80,
      },
    ],
  },
  [PokemonID.Doduo]: {
    name: 'Doduo',
    type: PokemonType.Flying,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.GreengrassSoybeans,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 3,
      seconds: 20,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 20,
    description:
      "To keep itself from being attacked while asleep, Doduo's two heads take turns staying awake. You'll only see both heads asleep together very rarely- perhaps only when Doduo feels completely safe.",
    evolvesInto: [
      {
        pokemon: PokemonID.Dodrio,
        level: 23,
        candies: 40,
      },
    ],
  },
  [PokemonID.Dodrio]: {
    name: 'Dodrio',
    type: PokemonType.Flying,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.GreengrassSoybeans,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 40,
      seconds: 0,
    },
    carryLimit: 21,
    friendshipPointsNeeded: 12,
    recruitExperience: 60,
    recruitShards: 155,
    description:
      "Dodrio usually sleeps standing up, its three heads taking turns so that at least one is always awake. When Dodrio is truly exhausted, it seems even the head that's on watch duty may doze off.",
  },
  [PokemonID.Gastly]: {
    name: 'Gastly',
    type: PokemonType.Ghost,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.FieryHerb,
      IngredientID.PureOil,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 3,
      seconds: 20,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 20,
    description:
      'It always floats while it sleeps-perhaps because its body is 95% gaseous. If you approach a Gastly that you think is fast asleep, it may give you a sudden surprise as it dreams!',
    evolvesInto: [
      {
        pokemon: PokemonID.Haunter,
        level: 19,
        candies: 40,
      },
    ],
  },
  [PokemonID.Haunter]: {
    name: 'Haunter',
    type: PokemonType.Ghost,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.FieryHerb,
      IngredientID.PureOil,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 50,
      seconds: 0,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 12,
    recruitExperience: 62,
    recruitShards: 186,
    description:
      "This Pokémon fears the light and revels in the dark. You must never approach it, even when it's asleep. If a sleep-fogged Haunter licks you with its gaseous tongue, it may end up stealing your life-force.",
    evolvesInto: [
      {
        pokemon: PokemonID.Gengar,
        item: Item.LinkingCord,
        candies: 80,
      },
    ],
  },
  [PokemonID.Gengar]: {
    name: 'Gengar',
    type: PokemonType.Ghost,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.FieryHerb,
      IngredientID.PureOil,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 36,
      seconds: 40,
    },
    carryLimit: 18,
    friendshipPointsNeeded: 22,
    recruitExperience: 431,
    recruitShards: 1291,
    description:
      'If you feel a sudden chill, a Gengar may be sleeping close by. Apparently, it sometimes falls into a deep sleep while hiding in the shadow of a target it intends to curse.',
  },
  [PokemonID.Cubone]: {
    name: 'Cubone',
    type: PokemonType.Ground,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [IngredientID.SoothingCacao, IngredientID.WarmingGinger],
    baseFrequency: {
      hours: 1,
      minutes: 20,
      seconds: 0,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 9,
    recruitShards: 16,
    description:
      "It's been found crying in its sleep. Perhaps the tears come because it's dreaming of its deceased mother.",
    evolvesInto: [
      {
        pokemon: PokemonID.Marowak,
        level: 21,
        candies: 40,
      },
    ],
  },
  [PokemonID.Marowak]: {
    name: 'Marowak',
    type: PokemonType.Ground,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [IngredientID.SoothingCacao, IngredientID.WarmingGinger],
    baseFrequency: {
      hours: 0,
      minutes: 58,
      seconds: 20,
    },
    carryLimit: 15,
    friendshipPointsNeeded: 12,
    recruitExperience: 93,
    recruitShards: 197,
    description:
      "It's been observed lovingly clutching its bone even in its sleep. You sometimes see Marowak sleeping with its bone as a pillow-perhaps this means the Pokémon feels at ease.",
  },
  [PokemonID.Kangaskhan]: {
    name: 'Kangaskhan',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.GreengrassSoybeans,
      IngredientID.SoftPotato,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 16,
    recruitExperience: 416,
    recruitShards: 449,
    description:
      "Kangaskhan protects its child by keeping it in its pouch, even while sleeping. If the child wakes before its mother and leaves the pouch to play, you'd best not approach it or you may end up in trouble with its mother.",
  },
  [PokemonID.MrMime]: {
    name: 'Mr. Mime',
    type: PokemonType.Psychic,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.LargeLeek,
      IngredientID.SnoozyTomato,
      IngredientID.SoftPotato,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 17,
    friendshipPointsNeeded: 12,
    recruitExperience: 95,
    recruitShards: 284,
    description:
      "It is a master of pantomime. No one can tell if it's miming being asleep, or if it's actually asleep and pantomiming in its dreams.",
  },
  [PokemonID.Pinsir]: {
    name: 'Pinsir',
    type: PokemonType.Bug,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.FancyApple,
      IngredientID.Honey,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 40,
      seconds: 0,
    },
    carryLimit: 19,
    friendshipPointsNeeded: 16,
    recruitExperience: 235,
    recruitShards: 608,
    description:
      "Although it's tough, it can't handle cold well. On especially cold nights, it buries itself in the ground and sleeps. Apparently, its two impressive pincers always stick out aboveground when this happens.",
  },
  [PokemonID.Ditto]: {
    name: 'Ditto',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.LargeLeek,
      IngredientID.PureOil,
      IngredientID.SlowpokeTail,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 58,
      seconds: 20,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 16,
    recruitExperience: 219,
    recruitShards: 384,
    description:
      'There have been reports from around the world of Ditto falling asleep while still transformed into another Pokémon. Yet Ditto usually returns to normal when it relaxes, so this is a very rare sight.',
  },
  [PokemonID.Eevee]: {
    name: 'Eevee',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 1,
      seconds: 40,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 5,
    recruitExperience: 20,
    recruitShards: 36,
    description:
      'Thanks to its unstable genetic makeup, Eevee can evolve into a variety of forms. Perhaps in its sleep, it dreams about which form it will evolve into.',
    evolvesInto: [
      {
        pokemon: PokemonID.Vaporeon,
        item: Item.WaterStone,
        candies: 80,
      },
      {
        pokemon: PokemonID.Jolteon,
        item: Item.ThunderStone,
        candies: 80,
      },
      {
        pokemon: PokemonID.Flareon,
        item: Item.FireStone,
        candies: 80,
      },
      {
        pokemon: PokemonID.Espeon,
        sleptHours: 150,
        candies: 80,
      },
      {
        pokemon: PokemonID.Umbreon,
        sleptHours: 150,
        candies: 80,
      },
      {
        pokemon: PokemonID.Leafeon,
        item: Item.LeafStone,
        candies: 80,
      },
      {
        pokemon: PokemonID.Glaceon,
        item: Item.IceStone,
        candies: 80,
      },
      {
        pokemon: PokemonID.Sylveon,
        sleptHours: 150,
        candies: 80,
      },
    ],
  },
  [PokemonID.Vaporeon]: {
    name: 'Vaporeon',
    type: PokemonType.Water,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 51,
      seconds: 40,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 20,
    recruitExperience: 675,
    recruitShards: 729,
    description:
      "Its body's cellular structure is similar to water's molecular composition, so it can melt invisibly in water. When Vaporeon sleeps on land, you can observe it as closely as you like.",
  },
  [PokemonID.Jolteon]: {
    name: 'Jolteon',
    type: PokemonType.Electric,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ExtraHelpfulS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 36,
      seconds: 40,
    },
    carryLimit: 17,
    friendshipPointsNeeded: 20,
    recruitExperience: 443,
    recruitShards: 1147,
    description:
      "If you quietly approach a sleeping Jolteon, you can hear the crackling sound of electricity as it exhales. When its fur stands on end, that's a sign it's about to give off a jolt of electricity-so get away quick!",
  },
  [PokemonID.Flareon]: {
    name: 'Flareon',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.CookingPowerUpS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 45,
      seconds: 0,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 20,
    recruitExperience: 443,
    recruitShards: 1147,
    description:
      "It sleeps contentedly wrapped in its fluffy fur, which releases heat into the air to cool down Flareon's body. Perhaps Flareon is regulating its body temperature even while sleeping.",
  },
  [PokemonID.Chikorita]: {
    name: 'Chikorita',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.LargeLeek,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 13,
      seconds: 20,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 5,
    recruitExperience: 18,
    recruitShards: 39,
    description:
      "It's said that Chikorita uses the leaf on its head to determine the air's temperature and humidity and search for the coziest place to bed down. It often seems relaxed in sleep, as if it has found itself a great spot.",
    evolvesInto: [
      {
        pokemon: PokemonID.Bayleef,
        level: 12,
        candies: 40,
      },
    ],
  },
  [PokemonID.Bayleef]: {
    name: 'Bayleef',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.LargeLeek,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 55,
      seconds: 0,
    },
    carryLimit: 17,
    friendshipPointsNeeded: 12,
    recruitExperience: 116,
    recruitShards: 245,
    description:
      "The buds that ring Bayleef's neck give off a spicy aroma that perks people up. Maybe the Pokémon sleeping around Bayleef feel invigorated, too.",
    evolvesInto: [
      {
        pokemon: PokemonID.Meganium,
        level: 24,
        candies: 80,
      },
    ],
  },
  [PokemonID.Meganium]: {
    name: 'Meganium',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.LargeLeek,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 20,
    friendshipPointsNeeded: 20,
    recruitExperience: 574,
    recruitShards: 1033,
    description:
      "The fragrance given off by its flower soothes and calms emotions. Fewer Pokémon fight around Meganium-you'll often even see them sleeping peacefully side-by-side.",
  },
  [PokemonID.Cyndaquil]: {
    name: 'Cyndaquil',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.FieryHerb,
      IngredientID.SoothingCacao,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 58,
      seconds: 20,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 5,
    recruitExperience: 16,
    recruitShards: 42,
    description:
      'Apparently, it often sleeps curled up. On very rare occasions, a sleep-befuddled Cyndaquil will spout flames from its back while sleeping.',
    evolvesInto: [
      {
        pokemon: PokemonID.Quilava,
        level: 11,
        candies: 40,
      },
    ],
  },
  [PokemonID.Quilava]: {
    name: 'Quilava',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.FieryHerb,
      IngredientID.SoothingCacao,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 50,
      seconds: 0,
    },
    carryLimit: 18,
    friendshipPointsNeeded: 12,
    recruitExperience: 116,
    recruitShards: 245,
    description:
      "On very rare occasions, you'll see the flames on its back blaze brightly while it sleeps. It seems that no matter how high the flames burn, the fur covering Quilava's body absolutely never catches fire.",
    evolvesInto: [
      {
        pokemon: PokemonID.Typhlosion,
        level: 27,
        candies: 80,
      },
    ],
  },
  [PokemonID.Typhlosion]: {
    name: 'Typhlosion',
    type: PokemonType.Fire,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [
      IngredientID.FieryHerb,
      IngredientID.SoothingCacao,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 40,
      seconds: 0,
    },
    carryLimit: 23,
    friendshipPointsNeeded: 20,
    recruitExperience: 528,
    recruitShards: 1116,
    description:
      "It's said that when Typhlosion tosses and turns in its sleep, its fur rubs together and occasionally produces blasts of fire. Take care not to venture near a sleeping Typhlosion by accident!",
  },
  [PokemonID.Totodile]: {
    name: 'Totodile',
    type: PokemonType.Water,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [IngredientID.BeanSausage, IngredientID.PureOil],
    baseFrequency: {
      hours: 1,
      minutes: 15,
      seconds: 0,
    },
    carryLimit: 11,
    friendshipPointsNeeded: 5,
    recruitExperience: 20,
    recruitShards: 36,
    description:
      "This Pokémon is known to close one eye and rest just half its brain at a time, a practice called unihemispheric sleep. Perhaps it's keeping watch against an enemy attack.",
    evolvesInto: [
      {
        pokemon: PokemonID.Croconaw,
        level: 14,
        candies: 40,
      },
    ],
  },
  [PokemonID.Croconaw]: {
    name: 'Croconaw',
    type: PokemonType.Water,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [IngredientID.BeanSausage, IngredientID.PureOil],
    baseFrequency: {
      hours: 0,
      minutes: 56,
      seconds: 40,
    },
    carryLimit: 15,
    friendshipPointsNeeded: 12,
    recruitExperience: 126,
    recruitShards: 227,
    description:
      "It's known to rest one brain hemisphere at a time, with the eye on the opposite side closed. Perhaps this method of sleeping with alternating halves of its brain is a defense against enemy attacks.",
    evolvesInto: [
      {
        pokemon: PokemonID.Feraligatr,
        level: 23,
        candies: 80,
      },
    ],
  },
  [PokemonID.Feraligatr]: {
    name: 'Feraligatr',
    type: PokemonType.Water,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthVariableS,
    ingredients: [IngredientID.BeanSausage, IngredientID.PureOil],
    baseFrequency: {
      hours: 0,
      minutes: 46,
      seconds: 40,
    },
    carryLimit: 19,
    friendshipPointsNeeded: 20,
    recruitExperience: 574,
    recruitShards: 1033,
    description:
      'Feraligatr, too, is known to sleep by resting one brain hemisphere at a time. Be warned-it always keeps a vigilant eye on its surroundings and will rush at enemies as soon as it senses their presence.',
  },
  [PokemonID.Pichu]: {
    name: 'Pichu',
    type: PokemonType.Electric,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.FancyEgg,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 11,
      seconds: 40,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 20,
    description:
      "If you listen carefully while it's sleeping, you can hear the crackle of static electricity. Apparently, it sometimes discharges energy in its sleep-maybe because it's not yet skilled at storing electricity.",
    evolvesInto: [
      {
        pokemon: PokemonID.Pikachu,
        sleptHours: 50,
        candies: 20,
      },
    ],
  },
  [PokemonID.Cleffa]: {
    name: 'Cleffa',
    type: PokemonType.Fairy,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.Metronome,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.GreengrassSoybeans,
      IngredientID.Honey,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 33,
      seconds: 20,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 25,
    recruitShards: 27,
    description:
      'Its body sways as it sleeps, as if rocked in a cradle. Its swaying silhouette looks just like a star that twinkles in the night sky.',
    evolvesInto: [
      {
        pokemon: PokemonID.Clefairy,
        sleptHours: 50,
        candies: 20,
      },
    ],
  },
  [PokemonID.Igglybuff]: {
    name: 'Igglybuff',
    type: PokemonType.Fairy,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergyForEveryoneS,
    ingredients: [
      IngredientID.Honey,
      IngredientID.PureOil,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 26,
      seconds: 40,
    },
    carryLimit: 8,
    friendshipPointsNeeded: 5,
    recruitExperience: 11,
    recruitShards: 12,
    description:
      'Its soft and elastic body makes it bounce even in its sleep. On very rare occasions, it apparently practices its singing in its dreams.',
    evolvesInto: [
      {
        pokemon: PokemonID.Jigglypuff,
        sleptHours: 50,
        candies: 20,
      },
    ],
  },
  [PokemonID.Togepi]: {
    name: 'Togepi',
    type: PokemonType.Fairy,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.Metronome,
    ingredients: [
      IngredientID.FancyEgg,
      IngredientID.SoothingCacao,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 20,
      seconds: 0,
    },
    carryLimit: 8,
    friendshipPointsNeeded: 5,
    recruitExperience: 18,
    recruitShards: 39,
    description:
      'It rolls around in its shell as it sleeps. Legend has it that happiness will come to those who can successfully stand up a sleeping Togepi.',
    evolvesInto: [
      {
        pokemon: PokemonID.Togetic,
        sleptHours: 50,
        candies: 20,
      },
    ],
  },
  [PokemonID.Togetic]: {
    name: 'Togetic',
    type: PokemonType.Fairy,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.Metronome,
    ingredients: [
      IngredientID.FancyEgg,
      IngredientID.SoothingCacao,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 3,
      seconds: 20,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 12,
    recruitExperience: 76,
    recruitShards: 161,
    description:
      'It sometimes sleeps while floating and apparently only moves its wings intermittently while doing so. Perhaps some sort of mysterious power is keeping it in the air.',
    evolvesInto: [
      {
        pokemon: PokemonID.Togekiss,
        item: Item.ShinyStone,
        candies: 80,
      },
    ],
  },
  [PokemonID.Mareep]: {
    name: 'Mareep',
    type: PokemonType.Electric,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeStrengthM,
    ingredients: [IngredientID.FancyEgg, IngredientID.FieryHerb],
    baseFrequency: {
      hours: 1,
      minutes: 16,
      seconds: 40,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 5,
    recruitExperience: 11,
    recruitShards: 13,
    description:
      "When Mareep rolls over in its sleep, its fluffy coat of wool rubs together and builds a static charge. This apparently turns into an electric current that flows into Mareep's tail, sometimes causing it to heat rapidly and start glowing at the tip.",
    evolvesInto: [
      {
        pokemon: PokemonID.Flaaffy,
        level: 11,
        candies: 40,
      },
    ],
  },
  [PokemonID.Flaaffy]: {
    name: 'Flaaffy',
    type: PokemonType.Electric,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeStrengthM,
    ingredients: [IngredientID.FancyEgg, IngredientID.FieryHerb],
    baseFrequency: {
      hours: 0,
      minutes: 55,
      seconds: 0,
    },
    carryLimit: 11,
    friendshipPointsNeeded: 12,
    recruitExperience: 79,
    recruitShards: 121,
    description:
      'If its coat becomes fully charged with electricity, its tail lights up. You can see this happen very rarely while it sleeps, too. But be careful-Flaaffy can fire off hairs that zap on impact!',
    evolvesInto: [
      {
        pokemon: PokemonID.Ampharos,
        level: 23,
        candies: 80,
      },
    ],
  },
  [PokemonID.Ampharos]: {
    name: 'Ampharos',
    type: PokemonType.Electric,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeStrengthM,
    ingredients: [IngredientID.FancyEgg, IngredientID.FieryHerb],
    baseFrequency: {
      hours: 0,
      minutes: 41,
      seconds: 40,
    },
    carryLimit: 15,
    friendshipPointsNeeded: 20,
    recruitExperience: 397,
    recruitShards: 715,
    description:
      "The light from its tail can be seen from space. It's said that this Pokémon usually keeps the light off, but if you see a light shining far off in the distance at night, perhaps it's a soundly sleeping Ampharos.",
  },
  [PokemonID.Sudowoodo]: {
    name: 'Sudowoodo',
    type: PokemonType.Rock,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeStrengthM,
    ingredients: [
      IngredientID.GreengrassSoybeans,
      IngredientID.SnoozyTomato,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 6,
      seconds: 40,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 7,
    recruitExperience: 23,
    recruitShards: 41,
    description:
      'It seems this Pokémon keeps up its tree mimicry in its sleep to avoid being attacked. But apparently, once in a long while, it lets itself go and sleeps laid out on the ground.',
  },
  [PokemonID.Espeon]: {
    name: 'Espeon',
    type: PokemonType.Psychic,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeStrengthM,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 40,
      seconds: 0,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 20,
    recruitExperience: 443,
    recruitShards: 1147,
    description:
      "It bathes in the sunshine during the day and builds up psychic power in the orb on its forehead. It's said to be averse to battling at night, so it might be easier than you'd expect to come across an Espeon deep in sleep.",
  },
  [PokemonID.Umbreon]: {
    name: 'Umbreon',
    type: PokemonType.Dark,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 53,
      seconds: 20,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 20,
    recruitExperience: 583,
    recruitShards: 894,
    description:
      "When exposed to the moon's aura at night, the rings on its body glow. It's said to be nocturnal, so it might be very difficult to find an Umbreon sleeping at night.",
  },
  [PokemonID.Slowking]: {
    name: 'Slowking',
    type: PokemonType.Water,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergizingCheerS,
    ingredients: [
      IngredientID.SlowpokeTail,
      IngredientID.SoothingCacao,
      IngredientID.SnoozyTomato,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 56,
      seconds: 40,
    },
    carryLimit: 11,
    friendshipPointsNeeded: 20,
    recruitExperience: 719,
    recruitShards: 1103,
    description:
      "This Pokémon is called the Sage of the Sea. It's said that a Slowking's head is always brimming with world-changing ideas, even as it sleeps, but then it forgets them all upon waking.",
  },
  [PokemonID.Wobbuffet]: {
    name: 'Wobbuffet',
    type: PokemonType.Psychic,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergizingCheerS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.PureOil,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 58,
      seconds: 20,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 7,
    recruitExperience: 29,
    recruitShards: 31,
    description:
      "It desperately tries to keep its black tail hidden. Though it keeps up the effort even while asleep, it's said that when Wobbuffet sleeps deeply and drops its guard, its tail can be seen on full display.",
  },
  [PokemonID.Heracross]: {
    name: 'Heracross',
    type: PokemonType.Bug,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [IngredientID.Honey, IngredientID.TastyMushroom],
    baseFrequency: {
      hours: 0,
      minutes: 41,
      seconds: 40,
    },
    carryLimit: 15,
    friendshipPointsNeeded: 16,
    recruitExperience: 286,
    recruitShards: 515,
    description:
      'Heracross loves sweet sap and will scour whole forests for it. When the search is particularly hard, Heracross grows exhausted and may even end up nodding off while still licking the sap it finds.',
  },
  [PokemonID.Houndour]: {
    name: 'Houndour',
    type: PokemonType.Dark,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.FieryHerb,
      IngredientID.LargeLeek,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 21,
      seconds: 40,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 8,
    recruitShards: 17,
    description:
      'Houndour communicates with its fellows using a variety of cries. It has also been found howling in its sleep, as if perhaps dreaming that it is out hunting with the rest of the pack.',
    evolvesInto: [
      {
        pokemon: PokemonID.Houndoom,
        level: 18,
        candies: 40,
      },
    ],
  },
  [PokemonID.Houndoom]: {
    name: 'Houndoom',
    type: PokemonType.Dark,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.FieryHerb,
      IngredientID.LargeLeek,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 55,
      seconds: 0,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 12,
    recruitExperience: 144,
    recruitShards: 303,
    description:
      "Houndoom breathes flames when it's angry and, on rare occasions, when it's asleep. Perhaps it's dreaming of fighting other Houndoom to choose the leader of the pack.",
  },
  [PokemonID.Larvitar]: {
    name: 'Larvitar',
    type: PokemonType.Rock,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.GreengrassSoybeans,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 20,
      seconds: 0,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 5,
    recruitExperience: 30,
    recruitShards: 54,
    description:
      'Larvitar feeds on soil. On very rare occasions you might find one holding a half-eaten clump of earth as it sleeps. Perhaps it grew sleepy after filling its belly.',
    evolvesInto: [
      {
        pokemon: PokemonID.Pupitar,
        level: 23,
        candies: 40,
      },
    ],
  },
  [PokemonID.Pupitar]: {
    name: 'Pupitar',
    type: PokemonType.Rock,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.GreengrassSoybeans,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 0,
      seconds: 0,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 12,
    recruitExperience: 156,
    recruitShards: 281,
    description:
      "Asleep or awake, this Pokémon never stays still even though it's a pupa. It's said that Pupitar may vent gas from its body and launch itself high into the sky like a rocket even while it sleeps.",
    evolvesInto: [
      {
        pokemon: PokemonID.Tyranitar,
        level: 41,
        candies: 100,
      },
    ],
  },
  [PokemonID.Tyranitar]: {
    name: 'Tyranitar',
    type: PokemonType.Dark,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.GreengrassSoybeans,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 45,
      seconds: 0,
    },
    carryLimit: 19,
    friendshipPointsNeeded: 25,
    recruitExperience: 1432,
    recruitShards: 2578,
    description:
      "Tyranitar possesses both overwhelming power and a body that can't be harmed by any sort of attack. It takes no heed of its surroundings even in its sleep, so you can see it in a truly superb sleeping position with its limbs thrown wide.",
  },
  [PokemonID.Slakoth]: {
    name: 'Slakoth',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.Honey,
      IngredientID.SnoozyTomato,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 21,
      seconds: 40,
    },
    carryLimit: 7,
    friendshipPointsNeeded: 5,
    recruitExperience: 11,
    recruitShards: 12,
    description:
      "Slakoth spends nearly all its time in a day sprawled out, trying to use as little energy as possible. Drowsy Power is the only thing that can successfully lure it to come and sleep by Snorlax's side.",
    evolvesInto: [
      {
        pokemon: PokemonID.Vigoroth,
        level: 14,
        candies: 40,
      },
    ],
  },
  [PokemonID.Vigoroth]: {
    name: 'Vigoroth',
    type: PokemonType.Normal,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.Honey,
      IngredientID.SnoozyTomato,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 53,
      seconds: 20,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 12,
    recruitExperience: 122,
    recruitShards: 187,
    description:
      "This Pokémon is incapable of sitting still. It's said that Vigoroth's blood is so agitated that it's unable to sleep deeply, even when it seems at first glance to be fast asleep.",
    evolvesInto: [
      {
        pokemon: PokemonID.Slaking,
        level: 27,
        candies: 40,
      },
    ],
  },
  [PokemonID.Slaking]: {
    name: 'Slaking',
    type: PokemonType.Normal,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.Honey,
      IngredientID.SnoozyTomato,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 3,
      seconds: 20,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 22,
    recruitExperience: 1108,
    recruitShards: 1196,
    description:
      "It is the world's laziest Pokémon, spending all day lying down and lolling about. On very rare occasions you might even see a Slaking that dozed off while snacking on the grass around it.",
  },
  [PokemonID.Sableye]: {
    name: 'Sableye',
    type: PokemonType.Dark,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.PureOil,
      IngredientID.SoothingCacao,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 0,
      seconds: 0,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 16,
    recruitExperience: 180,
    recruitShards: 465,
    description:
      "Sableye feeds on gemstone crystals. You sometimes see it sleeping while fondly clutching the gemstones it has gathered. Perhaps it's dreaming of eating them until its belly is stuffed.",
  },
  [PokemonID.Gulpin]: {
    name: 'Gulpin',
    type: PokemonType.Poison,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.DreamShardMagnetVariableS,
    ingredients: [
      IngredientID.GreengrassSoybeans,
      IngredientID.Honey,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 38,
      seconds: 20,
    },
    carryLimit: 8,
    friendshipPointsNeeded: 5,
    recruitExperience: 11,
    recruitShards: 12,
    description:
      "You often see Gulpin moving its mouth in its sleep. Since almost all its body is its stomach, it's said that when Gulpin sleeps with its mouth shut, that means it's digesting, and when its mouth is wide open, its stomach is empty.",
    evolvesInto: [
      {
        pokemon: PokemonID.Swalot,
        level: 20,
        candies: 40,
      },
    ],
  },
  [PokemonID.Swalot]: {
    name: 'Swalot',
    type: PokemonType.Poison,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.DreamShardMagnetVariableS,
    ingredients: [
      IngredientID.GreengrassSoybeans,
      IngredientID.Honey,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 58,
      seconds: 20,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 12,
    recruitExperience: 158,
    recruitShards: 170,
    description:
      "It sometimes falls asleep with its cavernous mouth wide open. Perhaps it's dreaming that it found a huge meal and is trying to swallow it whole.",
  },
  [PokemonID.Swablu]: {
    name: 'Swablu',
    type: PokemonType.Flying,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.FancyEgg,
      IngredientID.GreengrassSoybeans,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 10,
      seconds: 0,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 5,
    recruitExperience: 8,
    recruitShards: 17,
    description:
      "This Pokémon has been seen curled up asleep with its light and fluffy wings folded, looking just like a cottony hat. Perhaps Swablu is dreaming of being perched neatly atop someone's head.",
    evolvesInto: [
      {
        pokemon: PokemonID.Altaria,
        level: 26,
        candies: 40,
      },
    ],
  },
  [PokemonID.Altaria]: {
    name: 'Altaria',
    type: PokemonType.Dragon,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.ChargeEnergyS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.FancyEgg,
      IngredientID.GreengrassSoybeans,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 1,
      seconds: 40,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 12,
    recruitExperience: 170,
    recruitShards: 306,
    description:
      'It sleeps wrapped inside its wings, looking like a cottony cloud. Nestled within such soft, beautiful wings, the soundly snoozing Altaria may well be enjoying the most comfortable sleep ever.',
  },
  [PokemonID.Absol]: {
    name: 'Absol',
    type: PokemonType.Dark,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.SoothingCacao,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 51,
      seconds: 40,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 16,
    recruitExperience: 263,
    recruitShards: 556,
    description:
      "Its curved, bow-like horn remains vigilant even while Absol sleeps. It's said that this Pokémon's ability to detect danger is strong even as it slumbers.",
  },
  [PokemonID.Wynaut]: {
    name: 'Wynaut',
    type: PokemonType.Psychic,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergizingCheerS,
    ingredients: [
      IngredientID.FancyApple,
      IngredientID.PureOil,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 36,
      seconds: 40,
    },
    carryLimit: 7,
    friendshipPointsNeeded: 5,
    recruitExperience: 11,
    recruitShards: 12,
    description:
      "Even a sleeping Wynaut will always have a big, happy smile on its face. If it's slapping the ground with its black tail, it may be feeling restless and angry.",
    evolvesInto: [
      {
        pokemon: PokemonID.Wobbuffet,
        level: 11,
        candies: 20,
      },
    ],
  },
  [PokemonID.Spheal]: {
    name: 'Spheal',
    type: PokemonType.Ice,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.PureOil,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 33,
      seconds: 20,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 5,
    recruitExperience: 11,
    recruitShards: 12,
    description:
      "It's been found merrily clapping its fins while asleep on its back. It makes you want to ask Spheal what sort of happy things it was dreaming of after it wakes.",
    evolvesInto: [
      {
        pokemon: PokemonID.Sealeo,
        level: 24,
        candies: 40,
      },
    ],
  },
  [PokemonID.Sealeo]: {
    name: 'Sealeo',
    type: PokemonType.Ice,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.PureOil,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 6,
      seconds: 40,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 12,
    recruitExperience: 158,
    recruitShards: 170,
    description:
      "Sealeo's nose and the white whiskers around it are very sensitive. It's said that this Pokémon twitches its whiskers and touches them to the ground even while sleeping to sense the environment around it.",
    evolvesInto: [
      {
        pokemon: PokemonID.Walrein,
        level: 33,
        candies: 80,
      },
    ],
  },
  [PokemonID.Walrein]: {
    name: 'Walrein',
    type: PokemonType.Ice,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Berries,
    mainSkill: MainSkill.IngredientMagnetS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.PureOil,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 50,
      seconds: 0,
    },
    carryLimit: 18,
    friendshipPointsNeeded: 20,
    recruitExperience: 468,
    recruitShards: 586,
    description:
      'Its strong tusks shatter even large chunks of ice. Walrein has been found sleeping with a tusk stuck in the ground-as if perhaps the Pokémon fell asleep while tending to it.',
  },
  [PokemonID.Bonsly]: {
    name: 'Bonsly',
    type: PokemonType.Rock,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.ChargeStrengthM,
    ingredients: [
      IngredientID.GreengrassSoybeans,
      IngredientID.SnoozyTomato,
      IngredientID.TastyMushroom,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 45,
      seconds: 0,
    },
    carryLimit: 8,
    friendshipPointsNeeded: 5,
    recruitExperience: 9,
    recruitShards: 16,
    description:
      "People have observed Bonsly appearing to cry in its sleep. You may worry that something has happened to it, but there's no need! Bonsly is just expelling water to adjust its body's fluid level.",
    evolvesInto: [
      {
        pokemon: PokemonID.Sudowoodo,
        level: 12,
        candies: 20,
      },
    ],
  },
  [PokemonID.MimeJr]: {
    name: 'MimeJr',
    type: PokemonType.Psychic,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [
      IngredientID.LargeLeek,
      IngredientID.SnoozyTomato,
      IngredientID.SoftPotato,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 11,
      seconds: 40,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 7,
    recruitShards: 20,
    description:
      "On rare occasions, it's been found sleeping atop a pantomimed bed. It's said that even in its sleep, Mime Jr. is putting its heart and soul into mimicking Mr. Mime, who can pantomime all sorts of things.",
    evolvesInto: [
      {
        pokemon: PokemonID.MrMime,
        level: 12,
        candies: 40,
      },
    ],
  },
  [PokemonID.Riolu]: {
    name: 'Riolu',
    type: PokemonType.Fighting,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.DreamShardMagnetS,
    ingredients: [
      IngredientID.FancyEgg,
      IngredientID.PureOil,
      IngredientID.SoftPotato,
    ],
    baseFrequency: {
      hours: 1,
      minutes: 10,
      seconds: 0,
    },
    carryLimit: 9,
    friendshipPointsNeeded: 5,
    recruitExperience: 8,
    recruitShards: 17,
    description:
      'Riolu is said to be tough and hard-working. The unusual position it takes when it sleeps sitting up- without even lying down-is just how Lucario does it. Perhaps Riolu is pushing itself hard, dreaming of the day it will evolve.',
    evolvesInto: [
      {
        pokemon: PokemonID.Lucario,
        sleptHours: 150,
        candies: 80,
      },
    ],
  },
  [PokemonID.Lucario]: {
    name: 'Lucario',
    type: PokemonType.Fighting,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.DreamShardMagnetS,
    ingredients: [
      IngredientID.FancyEgg,
      IngredientID.PureOil,
      IngredientID.SoftPotato,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 45,
      seconds: 0,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 20,
    recruitExperience: 443,
    recruitShards: 1147,
    description:
      "It's said that Lucario hardly ever lowers its guard, even in its sleep. Perhaps it's still reading the aura emanating from others, just as it does when it's awake.",
  },
  [PokemonID.Croagunk]: {
    name: 'Croagunk',
    type: PokemonType.Poison,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [IngredientID.BeanSausage, IngredientID.PureOil],
    baseFrequency: {
      hours: 1,
      minutes: 33,
      seconds: 20,
    },
    carryLimit: 10,
    friendshipPointsNeeded: 5,
    recruitExperience: 9,
    recruitShards: 16,
    description:
      "It's been seen inflating the poison sacs on its cheeks as it sleeps. Apparently, Croagunk is sometimes startled awake by the sound the poison sacs make as they inflate.",
    evolvesInto: [
      {
        pokemon: PokemonID.Wartortle,
      },
    ],
  },
  [PokemonID.Toxicroak]: {
    name: 'Toxicroak',
    type: PokemonType.Poison,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Ingredients,
    mainSkill: MainSkill.ChargeStrengthS,
    ingredients: [IngredientID.BeanSausage, IngredientID.PureOil],
    baseFrequency: {
      hours: 0,
      minutes: 56,
      seconds: 40,
    },
    carryLimit: 14,
    friendshipPointsNeeded: 12,
    recruitExperience: 126,
    recruitShards: 227,
    description:
      "It sometimes uses the poison sac at its throat as a cushion while it sleeps. Be careful-Toxicroak may suddenly punch its fists out even when sleeping contentedly. Perhaps it's practicing its Poison Jab in its dreams.",
  },
  [PokemonID.Magnezone]: {
    name: 'Magnezone',
    type: PokemonType.Steel,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.CookingPowerUpS,
    ingredients: [IngredientID.FieryHerb, IngredientID.PureOil],
    baseFrequency: {
      hours: 0,
      minutes: 51,
      seconds: 40,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 22,
    recruitExperience: 546,
    recruitShards: 1415,
    description:
      "Its screws and magnets spin even while it sleeps. It's said that a sleeping Magnezone emits signals of unknown purpose and receives signals of unknown origin, but researchers are divided on this point.",
  },
  [PokemonID.Togekiss]: {
    name: 'Togekiss',
    type: PokemonType.Fairy,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.Metronome,
    ingredients: [
      IngredientID.FancyEgg,
      IngredientID.SoothingCacao,
      IngredientID.WarmingGinger,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 43,
      seconds: 20,
    },
    carryLimit: 16,
    friendshipPointsNeeded: 22,
    recruitExperience: 722,
    recruitShards: 1300,
    description:
      "It's said that Togekiss is never seen anywhere near conflict or turmoil. If you ever see several of them sleeping contentedly, perhaps it's a sign that peace reigns in the area.",
  },
  [PokemonID.Leafeon]: {
    name: 'Leafeon',
    type: PokemonType.Grass,
    sleepType: SleepType.Dozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergizingCheerS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 50,
      seconds: 0,
    },
    carryLimit: 13,
    friendshipPointsNeeded: 20,
    recruitExperience: 443,
    recruitShards: 1147,
    description:
      "When you see Leafeon asleep in a patch of sunshine, you'll know it is using photosynthesis to produce clean air. Perhaps this nice, crisp air might help any Pokémon around Leafeon sleep deeply.",
  },
  [PokemonID.Glaceon]: {
    name: 'Glaceon',
    type: PokemonType.Ice,
    sleepType: SleepType.Slumbering,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.CookingPowerUpS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 53,
      seconds: 20,
    },
    carryLimit: 12,
    friendshipPointsNeeded: 20,
    recruitExperience: 443,
    recruitShards: 1147,
    description:
      "At first glance it may look defenseless as it dozes, but look closer. Glaceon completely freezes its fur, making its hairs stand out like needles, so that it's protected from enemies even while it sleeps.",
  },
  [PokemonID.Sylveon]: {
    name: 'Sylveon',
    type: PokemonType.Fairy,
    sleepType: SleepType.Snoozing,
    specialty: PokemonSpecialty.Skills,
    mainSkill: MainSkill.EnergyForEveryoneS,
    ingredients: [
      IngredientID.BeanSausage,
      IngredientID.MoomooMilk,
      IngredientID.SoothingCacao,
    ],
    baseFrequency: {
      hours: 0,
      minutes: 43,
      seconds: 20,
    },
    carryLimit: 15,
    friendshipPointsNeeded: 20,
    recruitExperience: 583,
    recruitShards: 894,
    description:
      "It sends a soothing aura from its ribbonlike feelers. Trainers that sleep beside a Sylveon are likely get a great night's sleep every time they hit the hay.",
  },
};
