export enum SubSkillID {
  BerryFindingS = 'BerryFindingS',
  DreamShardBonus = 'DreamShardBonus',
  EnergyRecoveryBonus = 'EnergyRecoveryBonus',
  EnergyRecoveryM = 'EnergyRecoveryM',
  EnergyRecoveryS = 'EnergyRecoveryS',
  HelpingBonus = 'HelpingBonus',
  HelpingSpeedM = 'HelpingSpeedM',
  HelpingSpeedS = 'HelpingSpeedS',
  IngredientFinderM = 'IngredientFinderM',
  IngredientFinderS = 'IngredientFinderS',
  InventoryUpL = 'InventoryUpL',
  InventoryUpM = 'InventoryUpM',
  InventoryUpS = 'InventoryUpS',
  ResearchEXPBonus = 'ResearchEXPBonus',
  SkillLevelUpM = 'SkillLevelUpM',
  SkillLevelUpS = 'SkillLevelUpS',
  SkillTriggerM = 'SkillTriggerM',
  SkillTriggerS = 'SkillTriggerS',
  SleepEXPBonus = 'SleepEXPBonus',
}
